version: '3'
services:
  api:
    build:
      context: .                 
      dockerfile: Dockerfile     
    container_name: apicrud-api
    ports:
      - '3000:3000'


  db:
    image: mysql:5.7
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todosdb
    ports:
      - '3306:3306'
    volumes:                       
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:                          
  mysql_data:
